on:
  push:
    branches:
      - master

name: 🚀 AutoDeploy Metalsigma
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 realizando el build
        run: |
          npm install
          npm run build

      - name: listando archivos de salida
        run: find build/ -print

      - name: 📂 sincronizando archivos con servidor
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.residencialosrobles.com
          username: deploy@testsub.residencialosrobles.com
          password: angel1997MASFINO.
          local-dir: build/
